package com.spartaglobal.java.lessons;

import java.util.Date;

public class LifePolicy extends Policy{
    private boolean isSmoker;

    // constructor generated by intellij
    public LifePolicy(String policyHolder, double premium, double maxCover, Date renewalDate, boolean isSmoker) {
        super("Life", policyHolder, premium, maxCover, renewalDate);
        this.isSmoker = isSmoker;
    }

    // constructor generated by intellij
    public LifePolicy(boolean isSmoker) {
        this.isSmoker = isSmoker;
    }

    // generated using generate feature in intellij
    public void setSmoker(boolean smoker) {
        isSmoker = smoker;
    }

    // generated using generate feature in intellij
    public boolean isSmoker() {
        return isSmoker;
    }

    @Override
    public boolean processClaim(double claimAmount, String claimReason) {
            System.out.println("Processing claim for life policy: " + claimReason);
            return claimAmount < getMaxCover();
    }

    // generated using generate feature in intellij
    @Override
    public String toString() {
        return "LifePolicy{" +
                "isSmoker=" + isSmoker +
                '}';
    }
}
